Remove use of __uint32_t in Rust code
Needed to upgrade bindgen from 0.59.0 to 0.63.0. Resolves the
following errors:

error[E0412]: cannot find type `__uint32_t` in crate `system_properties_bindgen`
  --> system/librustutils/system_properties.rs:69:40
   |
69 |     serial: system_properties_bindgen::__uint32_t,
   |                                        ^^^^^^^^^^ not found in `system_prop
erties_bindgen`

error[E0412]: cannot find type `__uint32_t` in crate `system_properties_bindgen`
   --> system/librustutils/system_properties.rs:106:43
    |
106 |             _: system_properties_bindgen::__uint32_t,
    |                                           ^^^^^^^^^^ not found in `system_
properties_bindgen`

error[E0412]: cannot find type `__uint32_t` in crate `system_properties_bindgen`
   --> system/librustutils/system_properties.rs:277:39
    |
277 |         _: system_properties_bindgen::__uint32_t,
    |                                       ^^^^^^^^^^ not found in `system_prop
erties_bindgen`

Test: Treehugger
Change-Id: I34469dbc3e1dea7c601b96246a60870d2ee10e06